### ISSUE TITLE
Looking for new maintainers 

### ISSUE THREAD

**Issue by sibelius** [react-native-camera/react-native-camera#3000]
I'm stepping down from maintaining react-native-camera

Please comment if you wanna maintain this package

Another direction would be deprecated this package (https://github.com/react-native-community/react-native-camera/issues/2942) and focus on expo-camera instead

**Comment by fabriziobertoglio1987** [comment]
This weekend I will give a look at the issue. Thanks

**Comment by doranteseduardo** [comment]
Considering that a lot of people and projects use this library, I'm sure this project must be kept alive.
I'll talk with my team, I'm sure we can maintain it.

**Comment by MateusAndrade** [comment]
I can help with that, but it would be amazing having someone focused on this project.

**Comment by mateosilguero** [comment]
Could i help ?

**Comment by msriaz** [comment]
I would love to help in maintaining this package.

**Comment by diegotsi** [comment]
Hi @sibelius! I can help!

**Comment by np6176a** [comment]
Me too!! @sibelius I would love to help maintain this project.

**Comment by sibelius** [comment]
to start review and answer or close issues and pull requests

merge pull requests that make sense after testing in android and ios device

**Comment by Yandamuri** [comment]
We are starting new project and thinking to use this package. Can we go ahead with this package or is it going to be stopped in the future?

**Comment by renatobenks** [comment]
@Yandamuri you can go ahead! it will just be stopped for while until be completely re-designed, in order to keep it supportable

**Comment by Yandamuri** [comment]
@renatobenks that's great to hear. Thanks  a lot.

**Comment by mattonit** [comment]
I hope it's not too late :) If you're still looking for maintainers, I'd be happy to help with keeping this repo alive

**Comment by russelRajitha** [comment]
I am using this app for lot of my projects. i'am really happy to be a contributor with this module and i see some issues like crashing android app are still open.

**Comment by Walesson** [comment]
I hope it's not too late, i wish i could help.

**Comment by mattonit** [comment]
@sibelius you've added a lot of new maintainers - can we close this issue or you are going to extend this group?

**Comment by tewarig** [comment]
well, I  started building apps with react-native in the lockdown of 2020, this package helped me a lot. I would like to give my free time to this.

**Comment by MarcoScabbiolo** [comment]
Hey @sibelius i'd be glad to help!

**Comment by tewarig** [comment]
hi, @sibelius I would also love to maintain this project.

**Comment by bkvirendra** [comment]
@sibelius, we have been using this package for a while now and would be more than happy to assist with further development.

**Comment by MarcoScabbiolo** [comment]
Thanks to everyone :heart: 
All hands on deck for the next version!!! #3100

**Comment by geonsangyoo** [comment]
@MarcoScabbiolo 
I always appreciate your team for making us to be able to use react-native-camera library. 😄 

Hopefully it is not too late, Is there a seat available as a maintainer?
I would like to onboard on your project and contribute to it more as much as I can, which would be my honor! ^^

Thank you 👍

**Comment by theasc** [comment]
I would also like to help :)

**Comment by ZacharyLangley** [comment]
The company I work for uses this package and I would like to be added as a maintainer.

**Comment by MarcoScabbiolo** [comment]
To anyone looking to contribute, please do so, permissions will be granted as they are needed, nothin prevents you from answering issues, and creating PRs.

**Comment by fabriziobertoglio1987** [comment]
can we have stalebot removed?

**Comment by mayank-budhiraja** [comment]
I am happy to contribute to the project.

**Comment by ShakeelAhmad-dev** [comment]
it's really good package ...
I want to contribute ...

**Comment by pke** [comment]
I would be able to help maintain this repo. At least merge fully tested PRs once in a while.
Also would bring in support for volume buttons as per #764 using non-obstrusive feature detection code (when the react native button bundle is available)

**Comment by pke** [comment]
> To anyone looking to contribute, please do so, permissions will be granted as they are needed, nothin prevents you from answering issues, and creating PRs.

@MarcoScabbiolo well PRs are piling up already. What prevents them from being merged? Without a clear direction it does not seem to make much sense to work on PRs if they get stale here.

For instance the lib still uses outdated ref handling. This could probably patched easily. I am working on it to patch it locally, since the current implementation does not allow the RNCamer to be mocked properly. But why maintain a PR alongside my branch when its never merged into main here?

**Comment by MarcoScabbiolo** [comment]
@pke Sorry if any other issues or discussions are misleading, I've already expressed my mind about this repo and stopped working on the v4 version. My recommendation for you and anyone else is to migrate to [react-native-vision-camera](https://github.com/mrousavy/react-native-vision-camera). There is also [a discussion](https://github.com/mrousavy/react-native-vision-camera) about making it the official successor of `react-native-camera`. If it was only up to me, I would officialy deprecate `react-native-camera` and encourage users to move to `react-native-vision-camera` but I'm not the only one calling the shots here and honestly I've been out of RN in general for while now.

**Comment by pke** [comment]
@MarcoScabbiolo oh very cool! I was not aware of the vision camera. And it works in Android too it seems. I like the frame snippets to integrate with frame analysing tooling.
I'll give it a try, thanks!

**Comment by kidculli** [comment]
I have tried using react-native-vision-camera however it is definitely not fit for production use. I encountered bugs that would cause my application to crash. react-native-camera is much more stable. We should at the very least revert the readme back instead of pushing people to use  react-native-vision-camera. 

Also we should advertise additional options

- https://github.com/teslamotors/react-native-camera-kit
- https://docs.expo.dev/versions/latest/sdk/camera/

**Comment by ahron1** [comment]
It seems there are many volunteers to maintain this. So why is it deprecated? A lot of people are already using this in prod. Why make them migrate if there's no shortage of maintainers?

**Comment by MarcoScabbiolo** [comment]
There is shortage of maintainability, not maintainers. It is deprecated because for several reasons the base code is unsustainable, specially in Android. The end-game of restructuring, refactoring and taking the project to a sustainable status is the same end-game react-native-vision-camera is aiming for, and is well on track to reach and way ahead of react-native-camera-v4 partly because it doesn't have to deal with the multiple backwards compatibility issues and braking changes that arise when attempting to refactor from the react-native-camera code, and mainly because it is under very active development.

This is why this has been deprecated and why react-native-vision-camera has been pointed out as the most viable successor. It doesn't mean it's the only option, there are others but their foundations are different. React-native-camera-kit is targeted to a specific use case (Tesla's) and expo's is well... Expo, not RN. What react-native-camera was to me and probably many of you too, is the general-purpose RN library to integrate with the native camera/s. And as I've said many times before, Expo native modules should expand RN ones adding their own Expo stuff, because Expo is built on top of RN, so Expo modules should be built on top of RN ones. It is a waste of resources to have a dedicated from-scratch camera module only for expo, when all of those resources could be dedicated to create a RN module compatible with Expo.

The deprecation notice really means: Keep using react-native-camera if you want, but all the people that have been working on it have agreed that the project is unsustainable and should be replaced. And we luckily have a successor to put our efforts into, to make it the next react-native-camera we can all use for many purposes and collaborate on.

And don't forget this is a community driven project, if you wan't to keep using react-native-camera and contribute on it you can resume the react-native-camera-v4 project or you can fork react-native-camera and create another potential module to use.

**Comment by Mattimus333** [comment]
> I have tried using react-native-vision-camera however it is definitely not fit for production use. I encountered bugs that would cause my application to crash. react-native-camera is much more stable. We should at the very least revert the readme back instead of pushing people to use react-native-vision-camera.
> 
> Also we should advertise additional options
> 
> * https://github.com/teslamotors/react-native-camera-kit
> * https://docs.expo.dev/versions/latest/sdk/camera/

Thank you for this.  React-native-vision-camera doesn't even npm install properly.  The "example" is straight up unusable it's so buggy.  Can't believe that's what this repo is suggesting people switch over to.  react-native-camera-kit looks pretty good.

**Comment by nes123** [comment]
> > I have tried using react-native-vision-camera however it is definitely not fit for production use. I encountered bugs that would cause my application to crash. react-native-camera is much more stable. We should at the very least revert the readme back instead of pushing people to use react-native-vision-camera.
> > Also we should advertise additional options
> > 
> > * https://github.com/teslamotors/react-native-camera-kit
> > * https://docs.expo.dev/versions/latest/sdk/camera/
> 
> Thank you for this. React-native-vision-camera doesn't even npm install properly. The "example" is straight up unusable it's so buggy. Can't believe that's what this repo is suggesting people switch over to. react-native-camera-kit looks pretty good.

React-native-camera-kit seems weak for the android use case. Any thoughts on that?

**Comment by mat2718** [comment]
@sibelius  i know that this library was discontinued. is there anyway i could become a maintainer for this library?

**Comment by ahron1** [comment]
> @sibelius i know that this library was discontinued. is there anyway i could become a maintainer for this library?

https://github.com/react-native-camera/react-native-camera/issues/3000#issuecomment-1010283718
