### ISSUE TITLE
Camera and photos are slightly zoomed

### ISSUE THREAD

**Issue by MrHjalmarsson** [react-native-camera/react-native-camera#3151]
# Bug Report

**Platforms**

iOS

**Versions**
- iOS: 
- react-native-camera: 3.42.0, 3.43.0
- react-native: 0.63.3
- react: 16.13.1

**Description/Current Behaviour**

Compared to native iOS camera both the camera canvas and the result photos after capturing are slightly zoomed.
This was not a problem in 3.40.0

**Expected Behaviour**

Photos and canvas to not be zoomed.

**Steps to Reproduce**

Take photo with react-native-camera.
I'm using ratio 1:1.

**Additionals**
Attaching two images, one of photo with native iOS camera and one with react-native-camera

![react-native-camera](https://user-images.githubusercontent.com/72252436/111763584-9d4bc480-88a2-11eb-95bc-13dc0069ec98.jpg)
![iOS-camera](https://user-images.githubusercontent.com/72252436/111763597-9fae1e80-88a2-11eb-991f-28806b2acd9b.jpg)

**Comment by cristianoccazinsp** [comment]
How are you setting the aspect ratio to 1:1? Remember that iOS only captures in 4:3, but the final picture is based on the View's dimensions you've set. So if you render the component in a view that is not exactly 1:1, the photo will end up in another aspect ratio.

**Comment by MrHjalmarsson** [comment]
@cristianoccazinsp I set the camera view dimensions to screen width and I set ratio to 1:1 like this:
`style={{ width: screenWidth, height: screenHeight }}`
`ratio={ '1:1' }`

Downgrading to 3.40.0 solves the issue for me.

**Comment by cristianoccazinsp** [comment]
I still don't know if the ratio prop works in iOS, I think it's only for
Android photos!

But your problem is right there, you are using screen width and screen
height. For 1:1, you should use screen width for both width and height
style.

In curious about what changed within those versions, but for me, using
styles has always been the only way to set aspect ratio in iOS.

**Comment by MrHjalmarsson** [comment]
@cristianoccazinsp sorry, typo in the comment above. I'm of course using screen width for both height and width.

**Comment by cristianoccazinsp** [comment]
Ok, I know what's your issue then. It's related to this change
https://github.com/react-native-camera/react-native-camera/pull/2992#issuecomment-802631232

The reason it doesn't happen to me is because I've reverted it on my own
branch, but it should get fixed once
https://github.com/react-native-camera/react-native-camera/pull/3113 is
merged, or the PR reverted.

You can also revert the PR change yourself, or set the pictureSize prop to
"Photo" (iOS only) to force the iOS preset configuration to use the right
one as before the buggy PR.

Let me know if that helps.

**Comment by MrHjalmarsson** [comment]
@cristianoccazinsp I'll try that! Thanks for the feedback!
Will let you know
