### ISSUE TITLE
on rotaing App continusely the camera is stuck at landscape mode

### ISSUE THREAD

**Issue by AjayShivanagol** [react-native-camera/react-native-camera#3164]
![Screenshot from 2021-03-31 00-25-11](https://user-images.githubusercontent.com/29257275/113041566-bc5a2880-91b7-11eb-941a-ad184c622360.png)

**Comment by fabriziobertoglio1987** [comment]
how do we know this is not emulator issue?

**Comment by AjayShivanagol** [comment]
@fabriziobertoglio1987 you are right it's an emulator issue I tried on a real device it's working fine.

**Comment by fabriziobertoglio1987** [comment]
@AjayShivanagol thanks a lot. Yes, it is unlucky but we have many issues that affect our ability to create React Native Apps, so we need to prioritize. We will allways have limited number of developers doing open source.

I believe we should have libraries that have no bugs/issues so that developers can be productive while building apps with reactnative. :peace_symbol: :pray: 

I believe the community should decide which issues needs to be prioritized. I just comment so I'll remember next time what was my last opinion on the matter.
